#!/usr/bin/env python3
"""Render the hardening-status block into a README from its use-protection-please plan.

The plan file is the single source of truth; this script is the only writer of the
README block. It is idempotent: running it twice produces a byte-identical README, which
is what makes --check usable as a CI gate.

    render_readme_table.py --plan docs/plans/use-protection-please.md --readme README.md
    render_readme_table.py --all --root .            # every unit under root
    render_readme_table.py --all --root . --check    # exit 1 if any README is stale

Stdlib only, Python 3.8+.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BEGIN = "<!-- HARDENING-TABLE:BEGIN"
END = "<!-- HARDENING-TABLE:END -->"
BEGIN_LINE = (
    BEGIN + " generated by use-protection-please"
    " — edit docs/plans/use-protection-please.md, not this block -->"
)

PLAN_NAME = "use-protection-please.md"
BAR_CELLS = 20
STAR = "★"

STATUSES = ("Completed", "Scheduled", "Incomplete", "N/A")

# Compliance frameworks and the gates that carry their TECHNICAL controls. This is shared
# reference data - the same for every unit - so it lives here, while WHICH frameworks are
# in scope is per-unit and declared in the plan file. Full criterion-level mapping and the
# "this is not a certification" rules are in COMPLIANCE.md.
FRAMEWORKS = {
    "soc2": ("SOC 2", """H-01 H-02 H-07 H-08 H-09 H-10 H-11 H-12 H-13 H-18 H-19 H-22
        H-26 H-27 H-33 H-37 H-38 H-39 C-01 C-02 C-03 C-07 C-09 C-10 C-11 C-12 C-13"""),
    "pci-dss": ("PCI DSS v4.0", """H-07 H-08 H-09 H-12 H-15 H-16 H-18 H-19 H-26 H-27
        H-34 H-35 C-01 C-03 C-04 C-05 C-07 C-08 C-09"""),
    "gdpr-pii": ("GDPR / PII", """H-01 H-20 H-34 H-35 H-39 C-01 C-02 C-03 C-04 C-05
        C-06 C-07 C-08 C-09 C-10 C-11"""),
    "hipaa": ("HIPAA", "H-07 H-12 C-03 C-04 C-07 C-09"),
    "eu-cra": ("EU CRA", "H-04 H-05 H-09 H-12 H-15 H-33 H-39 H-40 C-11 C-14"),
    "nist-ssdf": ("NIST SSDF", """H-03 H-04 H-06 H-08 H-09 H-10 H-12 H-13 H-15 H-22
        H-23 H-26 H-27 H-28 H-32 H-38 H-40 C-12 C-14"""),
}


def compliance_rows(meta, rows):
    """Per-framework technical-control coverage for the frameworks declared in scope."""
    declared = meta.get("compliance", "").lower()
    declared = declared.split("-", 1)[0] if declared.strip().startswith("none") else declared
    by_id = {r["id"]: r for r in rows}
    out = []
    for fid, (label, gate_str) in FRAMEWORKS.items():
        if fid not in declared:
            continue
        gates = [by_id[g] for g in gate_str.split() if g in by_id]
        live = [g for g in gates if g["status"] != "N/A"]
        if not live:
            continue
        met = sum(1 for g in live if g["status"] == "Completed")
        if met == len(live):
            mark = "✅"
        elif any(g["status"] == "Scheduled" for g in live):
            mark = "🗓"
        else:
            mark = "⬜"
        out.append((label, met, len(live), mark))
    return out

ROW_RE = re.compile(r"^\|\s*([HC]-\d+)\s*\|(.*)$")
HEADING_RE = re.compile(r"^###\s+(.*?)\s*$")
META_RE = re.compile(r"^\*\*(?P<key>[A-Za-z0-9 .]+)\*\*\s*:?\s*(?P<val>.*?)\s*$")


class PlanError(Exception):
    pass


# ---------------------------------------------------------------- parsing


def split_row(line: str):
    """Split a markdown table row into its cells."""
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|"):
        body = body[:-1]
    return [c.strip() for c in body.split("|")]


def normalise_status(raw: str) -> str:
    """Map a status cell onto one of the four legal tokens."""
    token = raw.strip().strip("`*_ ").rstrip(".")
    # tolerate decorated cells: "✅ Completed", "**Scheduled**", "n/a"
    token = re.sub(r"[^A-Za-z/ ]", "", token).strip()
    folded = token.lower().replace(" ", "")
    if folded in ("na", "n/a", "notapplicable"):
        return "N/A"
    for status in ("Completed", "Scheduled", "Incomplete"):
        if folded == status.lower():
            return status
    if not folded:
        return "Incomplete"
    raise PlanError(f"unrecognised status {raw!r} (expected one of {', '.join(STATUSES)})")


def parse_plan(path: Path):
    """Return (meta, rows, warnings) from a plan file."""
    text = path.read_text(encoding="utf-8")
    meta, rows, warnings = {}, [], []
    phase = "Unfiled"
    seen = set()

    # Gate IDs legitimately appear in OTHER tables - waivers reference a gate, the risk
    # register cites one. Only rows inside the '## Checklist' section are checklist rows;
    # without this scoping a waiver row reads as a duplicate gate and voids the parse.
    in_checklist = False

    for line in text.splitlines():
        if line.startswith('## '):
            in_checklist = line.strip().lower().startswith('## checklist')
            continue

        heading = HEADING_RE.match(line)
        if heading:
            phase = heading.group(1)
            continue

        m = META_RE.match(line)
        if m and not rows:
            meta.setdefault(m.group("key").strip().lower(), m.group("val"))

        if not in_checklist or not ROW_RE.match(line):
            continue

        cells = split_row(line)
        if len(cells) < 3:
            raise PlanError(f"{path}: malformed row: {line.strip()}")
        gate_id = cells[0]
        if gate_id in seen:
            raise PlanError(f"{path}: duplicate gate {gate_id}")
        seen.add(gate_id)

        gate = cells[1]
        status = normalise_status(cells[2])
        evidence = cells[3] if len(cells) > 3 else ""
        target = cells[4] if len(cells) > 4 else ""

        if status == "Scheduled" and not target:
            warnings.append(f"{gate_id}: Scheduled with no Target date -> counted Incomplete")
            status = "Incomplete"
        if status == "N/A" and not evidence:
            warnings.append(f"{gate_id}: N/A with no reason in Evidence")

        rows.append(
            {
                "id": gate_id,
                "gate": gate,
                "status": status,
                "evidence": evidence,
                "target": target,
                "phase": phase,
                "star": STAR in gate,
            }
        )

    if not rows:
        raise PlanError(f"{path}: no gate rows found (expected rows starting '| H-01 |')")
    return meta, rows, warnings


# ---------------------------------------------------------------- rendering


def lead_token(raw: str, default: str = "", stop=(" - ", " — ", " (", ",")) -> str:
    """Keep the label at the head of a prose header field, drop the gloss after it."""
    val = (raw or "").strip()
    for sep in stop:
        val = val.split(sep)[0]
    val = val.split()[0].strip() if val.split() else ""
    return val or default


def phase_label(heading: str) -> str:
    """'Phase 3 — Code level' -> '3 — Code level'."""
    return re.sub(r"^Phase\s+", "", heading).strip()


def clean_gate(gate: str) -> str:
    return gate.replace(STAR, "").strip()


def progress_bar(fraction: float) -> str:
    filled = int(fraction * BAR_CELLS)
    filled = max(0, min(BAR_CELLS, filled))
    return "█" * filled + "░" * (BAR_CELLS - filled)


def rel_link(readme: Path, plan: Path) -> str:
    try:
        rel = plan.resolve().relative_to(readme.resolve().parent)
        return rel.as_posix()
    except ValueError:
        import os

        return Path(
            os.path.relpath(plan.resolve(), readme.resolve().parent)
        ).as_posix()


def render_block(meta, rows, readme: Path, plan: Path, link: str = "",
                 architect: str = "") -> str:
    counts = {s: 0 for s in STATUSES}
    per_phase = {}  # insertion-ordered: phase heading -> status counts
    for row in rows:
        counts[row["status"]] += 1
        bucket = per_phase.setdefault(row["phase"], {s: 0 for s in STATUSES})
        bucket[row["status"]] += 1

    tracked = counts["Completed"] + counts["Scheduled"] + counts["Incomplete"]
    pct = (counts["Completed"] / tracked) if tracked else 0.0

    stars = [r for r in rows if r["star"] and r["status"] != "N/A"]
    stars_done = sum(1 for r in stars if r["status"] == "Completed")

    # Header fields are prose in the plan file - authors legitimately write
    # "critical-path - eats untrusted bytes" or "survey (no tool probe was run)".
    # The block wants the label only, so keep the leading token and drop the gloss.
    tier = lead_token(meta.get("tier", ""), "unspecified")
    audited = lead_token(meta.get("audited", ""), "unrecorded", stop=(" by ",))
    depth = lead_token(meta.get("audit depth", ""), "")
    audited_str = f"{audited} ({depth})" if depth else audited

    # A mirrored README (a landing repo, or crates.io, where relative links do not
    # resolve) needs an absolute URL back to the one plan file rather than a second copy.
    link = link or rel_link(readme, plan)

    out = [
        BEGIN_LINE,
        "## Hardening status",
        "",
        f"**Tier** {tier} · **Audited** {audited_str} · "
        f"**v1.0.0 gates** {stars_done}/{len(stars)} · [Full checklist]({link})",
        "",
        f"`{progress_bar(pct)}` **{round(pct * 100)}%** &nbsp;·&nbsp; "
        f"{counts['Completed']} Completed · {counts['Scheduled']} Scheduled · "
        f"{counts['Incomplete']} Incomplete · {counts['N/A']} N/A",
        "",
        "| Phase | ✅ Completed | \U0001f5d3 Scheduled | ⬜ Incomplete | · N/A |",
        "|---|--:|--:|--:|--:|",
    ]
    for phase, c in per_phase.items():
        out.append(
            f"| {phase_label(phase)} | {c['Completed']} | {c['Scheduled']} | "
            f"{c['Incomplete']} | {c['N/A']} |"
        )
    out.append(
        f"| **Total** | **{counts['Completed']}** | **{counts['Scheduled']}** | "
        f"**{counts['Incomplete']}** | **{counts['N/A']}** |"
    )

    upcoming = sorted(
        (r for r in rows if r["status"] == "Scheduled"),
        key=lambda r: (r["target"], r["id"]),
    )[:3]
    if upcoming:
        items = " · ".join(
            f"{r['id']} {clean_gate(r['gate'])} ({r['target']})" for r in upcoming
        )
        out += ["", f"**Next up** — {items}"]

    comp = compliance_rows(meta, rows)
    if comp:
        out += [
            "",
            "**Compliance** — *technical controls evidenced by this audit. NOT a "
            "certification, an attestation, or an auditor's opinion.*",
            "",
            "| Framework | Technical controls met | |",
            "|---|--:|:--|",
        ]
        for label, met, total, mark in comp:
            out.append(f"| {label} | {met} / {total} | {mark} |")

    # Named accountability, last line of the block. Kept verbatim from the plan file so a
    # unit can name its own architect - never hardcode a person into the renderer.
    who = (architect or meta.get("architect", "")).strip()
    if who:
        out += ["", f"**Architect** — {who}"]

    out.append(END)
    return "\n".join(out)


def splice(readme_text: str, block: str) -> str:
    start = readme_text.find(BEGIN)
    end = readme_text.find(END)
    if start != -1 and end != -1 and end > start:
        return readme_text[:start] + block + readme_text[end + len(END) :]
    body = readme_text.rstrip("\n")
    sep = "\n\n---\n\n" if body else ""
    return body + sep + block + "\n"


# ---------------------------------------------------------------- driving


def process(plan: Path, readme: Path, check: bool, quiet: bool, link: str = "",
            architect: str = "") -> int:
    meta, rows, warnings = parse_plan(plan)
    for w in warnings:
        print(f"  ! {plan}: {w}", file=sys.stderr)

    block = render_block(meta, rows, readme, plan, link, architect)

    raw = readme.read_bytes() if readme.exists() else b""
    crlf = b"\r\n" in raw
    current = raw.decode("utf-8").replace("\r\n", "\n") if raw else ""
    updated = splice(current, block)

    if updated == current:
        if not quiet:
            print(f"  = {readme} up to date")
        return 0
    if check:
        print(f"  x {readme} is STALE - re-run without --check", file=sys.stderr)
        return 1

    payload = updated.replace("\n", "\r\n") if crlf else updated
    readme.write_text(payload, encoding="utf-8", newline="")
    print(f"  + {readme} updated")
    return 0


def discover(root: Path):
    for plan in sorted(root.rglob(PLAN_NAME)):
        if plan.parent.name != "plans" or plan.parent.parent.name != "docs":
            continue
        if any(part in {"target", "node_modules", ".git"} for part in plan.parts):
            continue
        unit = plan.parent.parent.parent
        readme = next(
            (p for p in sorted(unit.glob("*")) if p.name.lower() == "readme.md"),
            unit / "README.md",
        )
        yield plan, readme


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--plan", type=Path, help="path to a use-protection-please.md")
    ap.add_argument("--readme", type=Path, help="README to update")
    ap.add_argument("--all", action="store_true", help="sweep every unit under --root")
    ap.add_argument("--root", type=Path, default=Path("."), help="root for --all")
    ap.add_argument(
        "--link",
        default="",
        help="absolute URL for the 'Full checklist' link, instead of a relative path. "
        "Use when mirroring the block into another repo or a published page, so the "
        "mirror points back at the one plan file rather than a drifting second copy.",
    )
    ap.add_argument(
        "--architect",
        default="",
        help="override the Architect credit rendered at the foot of the block. Normally "
        "read from the plan file's **Architect** header field, so each unit names its "
        "own. Markdown is passed through, so a [Name](url) link works.",
    )
    ap.add_argument("--check", action="store_true", help="exit 1 if any README is stale")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if args.all:
        if args.link:
            ap.error("--link applies to a single --plan/--readme pair, not --all")
        pairs = list(discover(args.root))
        if not pairs:
            print(f"no {PLAN_NAME} found under {args.root}", file=sys.stderr)
            return 1
    elif args.plan:
        readme = args.readme or args.plan.parent.parent.parent / "README.md"
        pairs = [(args.plan, readme)]
    else:
        ap.error("pass --plan (with optional --readme) or --all")
        return 2

    rc = 0
    for plan, readme in pairs:
        try:
            rc |= process(plan, readme, args.check, args.quiet, args.link, args.architect)
        except PlanError as exc:
            print(f"  x {exc}", file=sys.stderr)
            rc |= 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
